### ISSUE TITLE
AttributeError: 'YOLO' object has no attribute 'yolo_model'

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [sthanhng/yoloface#35]
Traceback (most recent call last):
  File "yoloface_gpu.py", line 48, in <module>
    _main()
  File "yoloface_gpu.py", line 42, in _main
    detect_video(YOLO(args), args.video, args.output)
  File "D:\real_time_face_detect\yolo_realtime\yoloface-master\yolo\yolo.py", line 36, in __init__
    self.boxes, self.scores, self.classes = self._generate()
  File "D:\real_time_face_detect\yolo_realtime\yoloface-master\yolo\yolo.py", line 65, in _generate
    self.yolo_model.load_weights(self.model_path)
AttributeError: 'YOLO' object has no attribute 'yolo_model'

**Comment by Wojciech-A** [comment]
This error is caused by h5py. Do a downgrade to eg 2.10.0

**Comment by Akudor** [comment]
> This error is caused by h5py. Do a downgrade to eg 2.10.0

Hello, I already downgraded h5py to 2.10.0. I still have this problem.

self.yolo_model.load_weights(self.model_path)
AttributeError: 'YOLO' object has no attribute 'yolo_model'
